// Generated by Garaga version 1.1.0

//! # Starknet Verification Contract Tests
//!
//! This module contains comprehensive tests for the proof verification contract.
//! The tests use Starknet Foundry's testing features to verify proofs.
//!
//! ## Test Strategy
//! - Use real proof fixtures generated by the garaga CLI
//! - Test both positive (valid proof) and negative (invalid proof) cases

use deck_open_verifier::honk_verifier::{
    IUltraKeccakZKHonkVerifierDispatcherTrait, IUltraKeccakZKHonkVerifierLibraryDispatcher,
};
use snforge_std::fs::{FileTrait, read_txt};
use snforge_std::{DeclareResultTrait, declare};
use starknet::ClassHash;

/// Declare the UltraKeccakZKHonkVerifier contract for testing.
///
/// This function declares a new instance of the UltraKeccakZKHonkVerifier contract
///
/// # Arguments
/// * `name` - The contract name to declare
///
/// # Returns
/// * `ClassHash` - The class hash of the declared contract
///
/// # Example
/// ```cairo
/// let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
/// let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
/// ```
fn declare_contract(name: ByteArray) -> ClassHash {
    let class_hash = *declare(name).unwrap().contract_class().class_hash;
    class_hash
}

/// Test the verification function verify_ultra_keccak_zk_honk_proof with a valid proof.
///
/// This test demonstrates the complete verification flow:
/// 1. Declare the verification contract
/// 2. Load a pre-generated proof fixture
/// 3. Verify the proof on-chain
/// 4. Assert that verification succeeds
///
/// ## Test Setup
/// - Uses fork testing against Sepolia testnet to access required declared contracts maintained by
/// the garaga team - Loads proof calldata from `tests/proof_calldata.txt`
/// - To generate the calldata, you can use the garaga CLI:
/// ```bash
/// garaga calldata
///     --system ultra_keccak_zk_honk
///     --vk path/to/vk
///     --proof path/to/proof
///     --public-inputs path/to/public_inputs
///     --format snforge
///     --output-path path/to/tests
/// ```
/// This will generate a file `proof_calldata.txt` in the specified output path.
/// You can then use this file in the test.
///
/// ## Expected Behavior
/// - The proof should verify successfully
/// - The function should return Ok(public_inputs) containing the expected public inputs
/// - No panics or assertion failures should occur
#[test]
#[fork(url: "https://api.zan.top/public/starknet-sepolia/rpc/v0_10", block_tag: latest)]
fn test_verify_ultra_keccak_zk_honk_proof() {
    // Step 1: Declare the verification contract
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };

    // Step 2: Load the proof fixture generated by the script
    // This file contains the ultra_keccak_zk_honk proof calldata formatted for Starknet
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    // Step 3: Verify the proof on-chain
    // This calls the contract's verify_ultra_keccak_zk_honk_proof function with the loaded proof
    // data
    let result = dispatcher.verify_ultra_keccak_zk_honk_proof(calldata);

    // Step 4: Assert that verification succeeded
    // A valid proof should return Ok(public_inputs), not Err
    assert(result.is_ok(), 'Proof verification failed');
    // Optional: You can also verify the public inputs contain expected values
// let public_inputs = result.unwrap();
// assert(public_inputs.len() > 0, 'No public inputs');
// Additional assertions on the public input values can be added here
}

// ── Added by this project (not Garaga) ──────────────────────────────────
//
// The fixture is an opening of the deck the SHUFFLE circuit actually
// produced: its deck_hash is the hash_out of the a_0 shuffle proof checked in
// at circuits/shuffle_verifier/example_proof/. Proving the two circuits join
// up is the point -- a layout or encoding skew between them would otherwise
// only show up as an unopenable deck on a live table. Regenerate with
// scripts/prove_deck_open.mjs.

// The public inputs, in the exact order PokerGame::open_deck rebuilds them:
// deck_hash, chunk, k_total, then 4K ciphertext coordinates. Round 8's
// finding I was precisely this going wrong -- the deck could not be opened at
// all against the real verifier while a mock hid it -- so it is pinned here
// against the deployed contract rather than assumed.
//
// Positions used to be public inputs of their own, one per opened slot. They
// are DERIVED from chunk and k_total now (see circuits/deck_open/src/main.nr):
// that is what bought K = 16 -> 19, and what let the opening fold into the
// last shuffle proof at all. Nothing about who controls them changed -- the
// contract still derives every one of them from its own storage.
#[test]
fn test_public_inputs_are_hash_chunk_ktotal_then_cards() {
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    let public_inputs = dispatcher.verify_ultra_keccak_zk_honk_proof(calldata).unwrap();

    // 1 deck_hash + 1 chunk + 1 k_total + 76 card coordinates. The adapter
    // compares these against felts of low/high pairs, so this length is what
    // makes `expected.len() == actual.len() * 2` hold on the other side.
    assert(public_inputs.len() == 79, 'expected 79 public inputs');

    // deck_hash is the shuffle chain's hash_out for the a_0 shuffle -- the
    // same value circuits/shuffle_verifier/example_proof proves. The two
    // circuits joining up is the whole point; a layout or encoding skew
    // between them would otherwise only surface as an unopenable live deck.
    let deck_hash = *public_inputs.at(0);
    assert(deck_hash.low == 0xa85df438603c5f8f125591cd11c3924c, 'deck_hash.low');
    assert(deck_hash.high == 0x2d798b5c7a8e54145afc8db09e99c48f, 'deck_hash.high');

    // The fixture is chunk 1 of an eight-seat table: k_total = 2*8 + 5 = 21.
    assert(*public_inputs.at(1) == 1_u256, 'chunk is 1');
    assert(*public_inputs.at(2) == 21_u256, 'k_total is 21');

    // Chunk 1 covers raw slots 19..37, but only 19 and 20 are in play, so
    // every slot from the third onwards repeats position 20. Pinning that
    // here is what keeps the circuit's padding and open_deck's padding the
    // same convention -- they derive it independently, and a disagreement
    // would write the wrong ciphertext to the wrong deck position.
    let mut i: u32 = 2;
    while i != 19 {
        let mut f: u32 = 0;
        while f != 4 {
            assert(
                *public_inputs.at(3 + 4 * i + f) == *public_inputs.at(3 + 4 + f),
                'padding repeats slot 20',
            );
            f += 1;
        }
        i += 1;
    }
}

// Rejection is a PANIC, not an Err -- same as the shuffle verifier, and for
// the same reason: Garaga's MSM hints are derived from the proof, so
// corrupting it desynchronises them before any pairing check runs. Safe at
// every PokerGame call site, all of which assert on the result.
#[test]
#[should_panic(expected: ('Wrong GLV/FakeGLV decomposition', 'ENTRYPOINT_FAILED'))]
fn test_rejects_a_corrupted_proof() {
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file);

    let mut corrupted: Array<felt252> = array![];
    let mut i = 0;
    while i < calldata.len() {
        if i == 12 {
            corrupted.append(*calldata.at(i) + 1);
        } else {
            corrupted.append(*calldata.at(i));
        }
        i += 1;
    }

    dispatcher.verify_ultra_keccak_zk_honk_proof(corrupted.span());
}
