
[sncast.devnet0]
url = "http://127.0.0.1:5050/"
account = "devnet0"
accounts-file = "/home/x/.starknet_accounts/starknet_open_zeppelin_accounts.json"

[sncast.devnet1]
url = "http://127.0.0.1:5050/"
account = "devnet1"
accounts-file = "/home/x/.starknet_accounts/starknet_open_zeppelin_accounts.json"
