// The joint-key check, against REAL Grumpkin points.
//
// VerifierAdapter::verify_joint_key sums a table's registered key shares
// and compares against the joint key the dealer supplied to begin_shuffle.
// That is what stops a dealer imposing a key of their own choosing and
// reading every hole card at the table: the shuffle circuit takes the
// joint key as a public input and honestly proves re-randomisation under
// whatever key it is handed, and each seat's Schnorr proof only says that
// seat knows its own secret -- until this check, nothing tied the two
// together.
//
// cairo/tests/ can only cover how PokerGame handles the answer, because
// MockShuffleVerifier does no curve arithmetic. This covers the
// arithmetic. Fixtures come from scripts/joint_key_check.py, which
// independently asserts that the point-by-point sum equals
// (sum of secrets)*G.

use snforge_std::{ContractClassTrait, DeclareResultTrait, declare};
use zkpoker_verifier::adapter::{IShuffleVerifierDispatcher, IShuffleVerifierDispatcherTrait};

// 3 shares, seed 20260904. Generated by scripts/joint_key_check.py.
const PK0_X: u256 = u256 { low: 194832907768954394790680413128007861538, high: 37222705779953542780952501260393573017 };
const PK0_Y: u256 = u256 { low: 142770859926741081605239797661194602726, high: 42763694660889330978227029527611085507 };
const PK1_X: u256 = u256 { low: 95622290554835439536120117587405842462, high: 49119027213189153633323555233779647855 };
const PK1_Y: u256 = u256 { low: 212368912969865116781539454814995304608, high: 55326904112846906156483494456573728659 };
const PK2_X: u256 = u256 { low: 280672135536371551267253802440790140570, high: 6386820121154456958805107598231269519 };
const PK2_Y: u256 = u256 { low: 22055543581185237733252510939740498501, high: 11509490724105291452139459514189824119 };
const JOINT_X: u256 = u256 { low: 103953841592939312000243587208527278213, high: 52155123422478364501340658036230419407 };
const JOINT_Y: u256 = u256 { low: 192759540981694706271525335704320727395, high: 45982995379569309008140197948160453227 };
// -Y: same x, different key. Must be rejected.
const NEG_JOINT_Y: u256 = u256 { low: 200961464171553285581354164436118939294, high: 18340769233613868033721859537065586161 };

fn adapter() -> IShuffleVerifierDispatcher {
    let contract = declare("VerifierAdapter").unwrap().contract_class();
    // verify_joint_key routes to none of the four pinned verifiers, so
    // placeholder addresses are fine here.
    let (addr, _) = contract.deploy(@array![1, 2, 3, 4]).unwrap();
    IShuffleVerifierDispatcher { contract_address: addr }
}

fn shares() -> Span<u256> {
    array![PK0_X, PK0_Y, PK1_X, PK1_Y, PK2_X, PK2_Y].span()
}

#[test]
fn test_joint_key_accepts_the_real_sum() {
    assert(adapter().verify_joint_key(shares(), JOINT_X, JOINT_Y), 'sum should verify');
}

// The dealer-imposed key: a perfectly good curve point that simply is not
// the sum. This is the attack the check exists to stop.
#[test]
fn test_joint_key_rejects_a_key_that_is_not_the_sum() {
    // PK0 is on the curve and is somebody's real key -- just not the joint
    // one.
    assert(!adapter().verify_joint_key(shares(), PK0_X, PK0_Y), 'imposed key must fail');
}

// -Y has the SAME x as Y. Comparing only x-coordinates would accept it,
// and encrypting to -Y is a different key.
#[test]
fn test_joint_key_rejects_the_negated_key() {
    assert(!adapter().verify_joint_key(shares(), JOINT_X, NEG_JOINT_Y), 'negated key must fail');
}

// Drop one seat's share and the sum no longer matches -- this is the
// arithmetic backing PokerGame's rule that every seated player must have
// registered before the chain starts (round 8 finding D).
#[test]
fn test_joint_key_rejects_a_missing_share() {
    let short = array![PK0_X, PK0_Y, PK1_X, PK1_Y].span();
    assert(!adapter().verify_joint_key(short, JOINT_X, JOINT_Y), 'missing share must fail');
}

// Off-curve values do not obey the group law, so summing them proves
// nothing about any key anyone holds.
#[test]
fn test_joint_key_rejects_off_curve_shares() {
    let bad = array![1_u256, 1_u256, PK1_X, PK1_Y, PK2_X, PK2_Y].span();
    assert(!adapter().verify_joint_key(bad, JOINT_X, JOINT_Y), 'off-curve must fail');
}

// A table of nobody has no key, and an odd number of coordinates is not a
// list of points.
#[test]
fn test_joint_key_rejects_malformed_input() {
    let a = adapter();
    assert(!a.verify_joint_key(array![].span(), JOINT_X, JOINT_Y), 'empty must fail');
    assert(!a.verify_joint_key(array![PK0_X, PK0_Y, PK1_X].span(), JOINT_X, JOINT_Y), 'odd must fail');
}

// A full 23-seat table -- MAX_TABLE_SEATS, the worst case
// begin_shuffle can ever hand the adapter. Here for the cost, as much
// as the correctness: the sum is one ec_safe_add per seat, so it is
// linear and cheap next to any proof verification on this table.
fn max_shares() -> Span<u256> {
    array![
        u256 { low: 139248457489813260263872090490229877761, high: 57849090454550499870568416278379495742 },
        u256 { low: 307166338259791901774818256871902965921, high: 55063187107228620907162496181764223647 },
        u256 { low: 288857661313180160319114682598116573720, high: 29700135255295659746220609352390174777 },
        u256 { low: 285740313623487670059522408544128658063, high: 57326915159837103306322940142935357615 },
        u256 { low: 203046965223651782795155270292357326292, high: 28830425818862865941728604188325154254 },
        u256 { low: 131980584553663669875896200173045425483, high: 14662811348958831417668570762606702698 },
        u256 { low: 119755938940362571510150621978095997050, high: 26871765470643986623835753518092460585 },
        u256 { low: 230481155857611488220798283449125894061, high: 26234784582548588677072430095370591218 },
        u256 { low: 210882847545686026723932837787922912315, high: 23939451618929074420005940808899888288 },
        u256 { low: 86092251625073770258550411770537314233, high: 40009284479274443722998433206314225891 },
        u256 { low: 334201727109553058480008646954696561779, high: 44779315843588712982237537995439879236 },
        u256 { low: 152885636644388390450036696774870486710, high: 36600888351879227775683964559094141370 },
        u256 { low: 48805541246599305215595488335974504498, high: 51503234135757571208603118003161370958 },
        u256 { low: 307513142668234836266337299304847916146, high: 60256352202837508300788187085556122140 },
        u256 { low: 233233316309203801135936009176565292733, high: 10789836994424688915960970878486928966 },
        u256 { low: 279246002604045816376113224838743487887, high: 20798281156807809458756812850059022385 },
        u256 { low: 282973731935859596728334900102443290694, high: 22602714299986801128193134019872264569 },
        u256 { low: 208934975805285419714401181432405977073, high: 53027606028290567460766377079138033472 },
        u256 { low: 158150668668009505377368187678284151400, high: 3303537804969351368891159378555914000 },
        u256 { low: 188646012804032114949426450129960241096, high: 1812037066804675664431203661773716744 },
        u256 { low: 47740721652419760621383883557645959442, high: 26368810170615531672403911011676618802 },
        u256 { low: 38560540060777456894681802530801870794, high: 41020566934662153339302539847463126413 },
        u256 { low: 146969413629819338026251107806571646233, high: 27077477084018606346300890654431505536 },
        u256 { low: 160158024358377600186037630430692688105, high: 36612433210637972303126820829536786885 },
        u256 { low: 3151540846129836422379234886508873774, high: 51932331124504258417833522074022509869 },
        u256 { low: 332467925248044180638759695103998110061, high: 27167335245489485378496653540778239233 },
        u256 { low: 175153217124714149522868522643126608527, high: 13988830240474201448098753703477934666 },
        u256 { low: 192863361142564235637734162628236579248, high: 1107013629262045774233052606971863217 },
        u256 { low: 257665748668056242732413729031619634977, high: 14010998992857883980241533252310656314 },
        u256 { low: 2461452636893737756438699536234681755, high: 26554773405003755219798505055192462302 },
        u256 { low: 138196874757392446569807582721165316833, high: 54559550016103239942526785598168288765 },
        u256 { low: 299294556372046189782654004860600643135, high: 36423580108612980711456470065355023096 },
        u256 { low: 113372534882426799600549203458458755609, high: 17753733621983207522414249956013957298 },
        u256 { low: 145612209855895038752441600448643121464, high: 50660919126276119014821725222966982683 },
        u256 { low: 263560275602658197973756431721171488087, high: 6579414448801237983249219557035606710 },
        u256 { low: 5693308801182922597488672930403892077, high: 51408098114967142808078963481522297367 },
        u256 { low: 234978345399272752260953341207892344619, high: 10765156193626499446109073869675051436 },
        u256 { low: 76902407878463485918306918801369955821, high: 23850537365756991963019953009526079468 },
        u256 { low: 28056795650422025774483991167098010996, high: 5574606473593044635857378623046512205 },
        u256 { low: 143017299590284322520328275296808276647, high: 4039443477709083110528722162829721798 },
        u256 { low: 113615842943108228025003620086721185203, high: 8904522081202978503963764707606356385 },
        u256 { low: 138107621382629799187047947801960992593, high: 53080278319824957048407279147115223553 },
        u256 { low: 61624852618488280128963289002990672583, high: 15107771155886523024060654778416099095 },
        u256 { low: 301611671901301870068002440518521937610, high: 6043194153714456231703884321605834698 },
        u256 { low: 20781877813121369588884324790449278751, high: 1303002877885773407439470614832557153 },
        u256 { low: 167141837450039444042991813361061947299, high: 47350258751848531055512638062149039683 },
    ]
        .span()
}
const MAX_JOINT_X: u256 = u256 { low: 282672809244845527528441017162034951142, high: 143415547848131665585627996088480991 };
const MAX_JOINT_Y: u256 = u256 { low: 288155237562295495430607470295411232472, high: 56194492962454922137251853241419208492 };

#[test]
fn test_joint_key_at_max_table_size() {
    assert(adapter().verify_joint_key(max_shares(), MAX_JOINT_X, MAX_JOINT_Y), 'max table should verify');
}
