// GENERATED by scripts/check_client_crypto.mjs -- do not edit by hand.
//
// Fixtures produced by the BROWSER crypto in src/lib/ (schnorr.ts, dleq.ts,
// grumpkin.ts), run here against the real verifiers. This is the only thing
// standing between "the TS port looks right" and "the TS port produces proofs
// the deployed contract accepts". Every negative case below was confirmed to
// fail for the reason stated, not merely to fail.
//
// Regenerate: node scripts/check_client_crypto.mjs && snforge test

use snforge_std::{ContractClassTrait, DeclareResultTrait, declare};
use zkpoker_verifier::dleq::{IDleqVerifierDispatcher, IDleqVerifierDispatcherTrait};
use zkpoker_verifier::{IKeyVerifierDispatcher, IKeyVerifierDispatcherTrait};

fn dleq() -> IDleqVerifierDispatcher {
    let contract = declare("DleqVerifier").unwrap().contract_class();
    let (address, _) = contract.deploy(@array![]).unwrap();
    IDleqVerifierDispatcher { contract_address: address }
}

fn schnorr() -> IKeyVerifierDispatcher {
    let contract = declare("SchnorrKeyVerifier").unwrap().contract_class();
    let (address, _) = contract.deploy(@array![]).unwrap();
    IKeyVerifierDispatcher { contract_address: address }
}

// ─── Schnorr: src/lib/schnorr.ts ─────────────────────────────────────────


// secret 0x2b7e151628aed2a6abf7158809cf4f3c, nonce 0xa11ce5
fn schnorr_proof_0() -> (Array<felt252>, Array<felt252>) {
    let proof: Array<felt252> = array![
        0x7759fe5b8daab20318846568,
        0xcd3a6c163eab640e9f8114da,
        0xa6e1aaff18a63bc,
        0x0,
        0xe08c67b4d9fb697cffb9f55a904050e1,
        0x2e75e8bbd1f4804b3ed1af66cc60207c,
        0x7fefa6229501ac81a948bc0a44464c46,
        0x3b26268ed0e0ae4267b627c3683335f,
        0x14,
        0x972ab0c58ba4fd998089b10,
        0x491e11bcc9b725372a2503f9,
        0x23e17c162c2f71d3,
        0x0,
        0x16a94ecbbbecf40ef4c2d4ac,
        0x566ae951ac1ec30a0cd532a1,
        0x163ca6f6aa3366a7,
        0x0,
        0x621176f2fbb863c6c831a7541d41af48,
        0x1521f9eeb91c96ab7753eb52569b16cb9,
        0x71c99a28a0b7bbc46cb4eafb,
        0xa361ee07e9404fe902a26129,
        0x1fd8fa794b457b03,
        0x0,
        0x7059578fbeb816d9f3c86721,
        0x71b4f6c1f5bbe9378085011e,
        0x19d1b1aa5f3a071e,
        0x0,
        0x283c8749c440738e3dfec2daba091bdf,
        0x118fdfbade445c27ad435bdd84fb3c8d7,
    ];
    let public_inputs: Array<felt252> = array![
        0xcd6b3a731edfa5f6828210ad0a1ec09b,
        0x25e9e18413b5247a58f14371c70aa020,
        0x119d72392ac6cd960a4243de6026f5f8,
        0x15c359df1a69f4923273c595572decd3,
    ];
    (proof, public_inputs)
}

// secret 0x8e73b0f7da0e6452c810f32b809079e5, nonce 0xb0b0b0
fn schnorr_proof_1() -> (Array<felt252>, Array<felt252>) {
    let proof: Array<felt252> = array![
        0x5e434c2d075674d2a57c940,
        0xf3cfec79ace3322c8eba73df,
        0xf9684a17048bfea,
        0x0,
        0xf375ecad18950e51b3430fa1a4d0eca1,
        0x2f67165804c1d5f1fbef2e938accf13c,
        0xdcfc2ce3f634713eced1008b6649508b,
        0x54e0d95fffa385f667ab805649f2ac,
        0x14,
        0xbdff6eef68d1c70f5ca719cb,
        0xdd6881f2a86d24e515d5e212,
        0xd5cdacf1b2c2fdc,
        0x0,
        0xd822da76a471f6fbe1592218,
        0x6d137c1bc0c49aa02d294f03,
        0x1f0517c53dc29374,
        0x0,
        0x2e132cf09185f90a04b94b82dec918bd,
        0x47c07ee97342b61f876bb843e323dc29,
        0x95253901a72d33e1f3280828,
        0x11ee4902fc137ab042cb8cae,
        0x26ddbd857a5a3858,
        0x0,
        0x4cb40fa654d3163258df56fd,
        0xf9d826e269d17dd475b070a2,
        0x197683d2217d1155,
        0x0,
        0x488156a92b8dc3b0d1ae66c95e83e6b8,
        0x11aa956e80ffe0b43c6ee6f17e7e0b425,
    ];
    let public_inputs: Array<felt252> = array![
        0x992994a29b0e193347f651a5f14f462e,
        0x598d72a6c32bdf6b1b216b94e22b2f0,
        0xc198ca9df0ee98c9f908069c53af167e,
        0x73491d90db9c69ce324fbe62507521d,
    ];
    (proof, public_inputs)
}

// secret 0x62f8ead2522c6b7b3d5a1f0e4c9b8a71, nonce 0xcafe17
fn schnorr_proof_2() -> (Array<felt252>, Array<felt252>) {
    let proof: Array<felt252> = array![
        0xa2949ae989b992a852fcd9df,
        0x4ebab82a0cfa6368e76a4322,
        0x2940310ac14b6ee0,
        0x0,
        0xe1f8ecdaacf0cb4f4d6c7b6eb1ec38d7,
        0x1c78b2437e53ec211521631bfd7b2f32,
        0xe03ce8db4af0d5722405f08fb3423868,
        0x1745073def4fa35aaa6fb4cea5fbb1f,
        0x14,
        0xf766e354e59b67702deb5da0,
        0xd19f7eb14fef4dcd6b89381b,
        0xe2906d982daf002,
        0x0,
        0x9085b1fc1ed922a944ec9ff9,
        0xdb7d2ce463876aab1abab083,
        0x236d4484a93c0db,
        0x0,
        0x46d0ef5f3be173d8c6a30ed1269e235f,
        0x15bceca1b045d982cadf38cbb2455f9,
        0xc470a6f64cf527fb72548ab3,
        0x140d15dffe812167624e404,
        0x1747e5c7ca59baab,
        0x0,
        0x39659f713947c18aa3e22311,
        0x88f033cf6ddf09405aaf08fa,
        0x2024dec12ca646b8,
        0x0,
        0x463292b5c008eaa8e29e1406293630b3,
        0x48cc3c4c01a10a4a759f15d68d59321,
    ];
    let public_inputs: Array<felt252> = array![
        0x2dea1df7cdab1258514087863b3c0db0,
        0x222452e8ec3bb070377d6f06913cd5ea,
        0xf2bd7e84c1f0f1b7e5c760d5e321bc6,
        0x2545f334765f77d918605c6269682f8a,
    ];
    (proof, public_inputs)
}


#[test]
fn test_browser_schnorr_0_is_accepted() {
    let v = schnorr();
    let (proof, public_inputs) = schnorr_proof_0();
    assert(v.verify_key_ownership(proof.span(), public_inputs.span()), 'schnorr 0 rejected');
}

#[test]
fn test_browser_schnorr_1_is_accepted() {
    let v = schnorr();
    let (proof, public_inputs) = schnorr_proof_1();
    assert(v.verify_key_ownership(proof.span(), public_inputs.span()), 'schnorr 1 rejected');
}

#[test]
fn test_browser_schnorr_2_is_accepted() {
    let v = schnorr();
    let (proof, public_inputs) = schnorr_proof_2();
    assert(v.verify_key_ownership(proof.span(), public_inputs.span()), 'schnorr 2 rejected');
}

#[test]
fn test_browser_schnorr_rejects_a_tampered_challenge() {
    // e is the third felt of the calldata (rx, s, e, ..hint). A verifier that
    // took e from the caller instead of recomputing it would accept this --
    // that is the forgery the recompute exists to stop.
    let v = schnorr();
    let (proof, public_inputs) = schnorr_proof_0();
    let mut bad: Array<felt252> = array![];
    let mut i = 0;
    while i < proof.len() {
        if i == 2 { bad.append(*proof.at(i) + 1); } else { bad.append(*proof.at(i)); }
        i += 1;
    }
    assert(!v.verify_key_ownership(bad.span(), public_inputs.span()), 'tampered e accepted');
}

#[test]
fn test_browser_schnorr_rejects_a_foreign_public_key() {
    // Proof 0 replayed against key 1: the challenge binds to the key, so this
    // is the same rejection that stops a rogue-key registrant reusing someone
    // else's proof of knowledge.
    let v = schnorr();
    let (proof, _) = schnorr_proof_0();
    let (_, other_inputs) = schnorr_proof_1();
    assert(!v.verify_key_ownership(proof.span(), other_inputs.span()), 'foreign key accepted');
}

// ─── DLEQ: src/lib/dleq.ts ───────────────────────────────────────────────

// One party's individual share -- what answer_accusation posts.
fn dleq_individual() -> (Array<felt252>, Array<felt252>) {
    let proof: Array<felt252> = array![
        0x31a2616e473e15ba82b8285f6e6ff794,
        0xe2a9b2fd53263a4dd14fb5d6b97d1ed,
        0xfc6cb7fb3c5d1b489f8edbc9941d4c93,
        0x428a74df6f380e0ff71abbd6a971a2c,
        0x51726ec214c048c0ab590335,
        0xedd7f3f291699bf9e252e6b3,
        0x2d1ee4e9d520e5d7,
        0x0,
        0x78244afacbfcceda37872476,
        0x7503b2e5aa5d13f9f4071755,
        0x2f9ad2831484809,
        0x0,
        0x2fcd80e93a912728d1846c7ab6b59be5,
        0x104278c1a3a398e35ad6c734b57ce7a92,
        0xe42251d56c870cd54625bd72,
        0x661b2a78367a79e8befa88aa,
        0x71e5503dd86c078,
        0x0,
        0xf1909921e5e6a77764ef4e3c,
        0xd28f0b7e579ad7e9f092adcb,
        0x2d5ebb27e2097ffc,
        0x0,
        0x2ee0b89bceb47d4848f50a7593b1b230,
        0x47cb70900d53f79d5b1d66744023eeeb,
        0xb04d71ef362597ddb85d98ad,
        0x1f8e37d866553c6a2a2da8f5,
        0xd81ef3306d8a10c,
        0x0,
        0x42dc9ca4e04118ae850c909,
        0x29ebd8176a75c944531c605e,
        0x206fbbb3daf94723,
        0x0,
        0x2fcd80e93a912728d1846c7ab6b59be5,
        0x104278c1a3a398e35ad6c734b57ce7a92,
        0xe6e941604b8c23e3c9379bc1,
        0x1edcf3bf326b6dd5810ba8de,
        0x3abd96f42d69ad2,
        0x0,
        0xa7520f033372c0553035facd,
        0x13341c890b700ac215e78c60,
        0x55f0859dc2dc7e1,
        0x0,
        0x2ee0b89bceb47d4848f50a7593b1b230,
        0x47cb70900d53f79d5b1d66744023eeeb,
    ];
    let public_inputs: Array<felt252> = array![
        0xcd6b3a731edfa5f6828210ad0a1ec09b,
        0x25e9e18413b5247a58f14371c70aa020,
        0x119d72392ac6cd960a4243de6026f5f8,
        0x15c359df1a69f4923273c595572decd3,
        0x6886e7c981ee5f0e8afac37cbedd4af3,
        0x18e8c4570ca96d7f6da120d441dd6f7,
        0xbeba1330490c588fb640ebff60690bd6,
        0xeddda774026e91fa1d3e0e6f154bef3,
        0xd34c05c9880dc2a2f093b5c20f9adbf1,
        0x17567092b1adbee88b31d0473a029376,
        0x2ff06e9b219e1aaf50a896374453d092,
        0x20042850e6a3834269c6d30b6413ac74,
    ];
    (proof, public_inputs)
}

// 3 parties' shares aggregated into one proof against the joint key --
// the normal reveal path, flat in the number of players (PROTOCOL.md §6.2).
fn dleq_aggregate() -> (Array<felt252>, Array<felt252>) {
    let proof: Array<felt252> = array![
        0x536039c3a82a869bdc32acca83d66c28,
        0x16396a283d087f9f7c69e7967cd5a1fe,
        0xb13637fcf426dfe3c12ad653897ba832,
        0x38ec02a0344582af78065980b83839c,
        0xfc253588077b33145e862935,
        0x55fb6d7816357f0718850c34,
        0x289fd34451610b0e,
        0x0,
        0x6d7f263d35949f74a2666062,
        0x5f780ef89d30a2e73fdecdb,
        0x12de1025a41b9e44,
        0x0,
        0xd91f2cefec2496d8dedd550505939b8,
        0x6a5ebcec70e8b0c2db40ea1af84a2cd1,
        0x921464c2cb392eca970185bb,
        0x8ee65ec084f89e20775efe5f,
        0x5e31c7ef0bba231,
        0x0,
        0x2d4e5b21de8710ef366a0809,
        0x19ac95ae1f36874a4db2b747,
        0x196e995a164d84cf,
        0x0,
        0x652327e0b4d76434ae57ec1144ab9876,
        0x11414e4a26d3628513f1116956cffe11b,
        0x787a957d104143038ab3306a,
        0x8b928abd052064937598b6f1,
        0x2e86c1b961aef9b,
        0x0,
        0x86a45c0b4d89f8e6531594b0,
        0xafd70f4c7c22885176f8737d,
        0x2cebee131ec5f183,
        0x0,
        0xd91f2cefec2496d8dedd550505939b8,
        0x6a5ebcec70e8b0c2db40ea1af84a2cd1,
        0xae4eed6aa6ff332f6db3c7f1,
        0xe637dd03e99a94dfcd252959,
        0x2e3d6484659423c3,
        0x0,
        0x6792a7451ea68efe83298fbc,
        0xe721f2072a0ed7cea9fbe424,
        0x112c6491b7e04edc,
        0x0,
        0x652327e0b4d76434ae57ec1144ab9876,
        0x11414e4a26d3628513f1116956cffe11b,
    ];
    let public_inputs: Array<felt252> = array![
        0xa9ae922ced6e815d1a0a0f1e3d1d01c4,
        0x15745bc3fb5b00ce9a39c83aae352767,
        0x42e8252548ba63b27c9f7ff77c513edd,
        0x1b0d785fcb55df74c2b0ee6f9330af0f,
        0x6886e7c981ee5f0e8afac37cbedd4af3,
        0x18e8c4570ca96d7f6da120d441dd6f7,
        0xbeba1330490c588fb640ebff60690bd6,
        0xeddda774026e91fa1d3e0e6f154bef3,
        0xbca1d9d0ffbff7b4ca802c2afd9f6aa3,
        0x13de0990b2edca6ce048af75844740cf,
        0x2f83536f8e40147ecd7c8c0a23c0fcc4,
        0x290e0264e08aba42a857bb8335e3062,
    ];
    (proof, public_inputs)
}

// The hole-card commitment, recomputed the way reveal_hole_card recomputes it.
//
// A player commits to the COMBINED share at dealing time, before betting, and
// reopens it at showdown. The contract rebuilds this hash from the share and
// blinding it is handed and rejects anything that does not match, so if
// starknet.js and Cairo disagreed about poseidon_hash_span the player would
// commit fine and then be unable to show -- forfeiting the pot to a hash.
#[test]
fn test_browser_hole_commitment_matches_cairo() {
    let share_x = u256 { low: 0xbca1d9d0ffbff7b4ca802c2afd9f6aa3, high: 0x13de0990b2edca6ce048af75844740cf };
    let share_y = u256 { low: 0x2f83536f8e40147ecd7c8c0a23c0fcc4, high: 0x290e0264e08aba42a857bb8335e3062 };
    let blinding: felt252 = 0x5eed1;

    let recomputed = core::poseidon::poseidon_hash_span(
        array![
            share_x.low.into(), share_x.high.into(), share_y.low.into(), share_y.high.into(),
            blinding,
        ]
            .span(),
    );
    assert(recomputed == 0x5d449eba9f81ebe76360bb1375b174ba9ba8f5ca429b9f3add432c73f1ba073, 'hole commitment mismatch');
}

// The reveal path's public inputs, in the order verify_reveal_at builds them:
// the table's JOINT key, then the opened ciphertext's c1, then the combined
// share. None of the first four felts come from the caller on-chain -- they are
// read from storage the shuffle chain and the opening proof already fixed --
// so this pins that the client builds the same statement the contract will.
#[test]
fn test_browser_reveal_inputs_are_joint_key_then_c1_then_share() {
    let (_, public_inputs) = dleq_aggregate();
    assert(public_inputs.len() == 12, 'expected 12 felts');

    // joint key
    assert(*public_inputs.at(0) == 0xa9ae922ced6e815d1a0a0f1e3d1d01c4, 'joint x low');
    assert(*public_inputs.at(1) == 0x15745bc3fb5b00ce9a39c83aae352767, 'joint x high');
    assert(*public_inputs.at(2) == 0x42e8252548ba63b27c9f7ff77c513edd, 'joint y low');
    assert(*public_inputs.at(3) == 0x1b0d785fcb55df74c2b0ee6f9330af0f, 'joint y high');
    // c1 -- the DLEQ base H
    assert(*public_inputs.at(4) == 0x6886e7c981ee5f0e8afac37cbedd4af3, 'c1 x low');
    assert(*public_inputs.at(6) == 0xbeba1330490c588fb640ebff60690bd6, 'c1 y low');
    // the combined share D
    assert(*public_inputs.at(8) == 0xbca1d9d0ffbff7b4ca802c2afd9f6aa3, 'share x low');
    assert(*public_inputs.at(10) == 0x2f83536f8e40147ecd7c8c0a23c0fcc4, 'share y low');
}

#[test]
fn test_browser_dleq_individual_share_is_accepted() {
    let v = dleq();
    let (proof, public_inputs) = dleq_individual();
    assert(v.verify_decryption_share(proof.span(), public_inputs.span()), 'individual rejected');
}

#[test]
fn test_browser_dleq_aggregate_is_accepted() {
    let v = dleq();
    let (proof, public_inputs) = dleq_aggregate();
    assert(v.verify_decryption_share(proof.span(), public_inputs.span()), 'aggregate rejected');
}

#[test]
fn test_browser_dleq_aggregate_opens_the_right_card() {
    // The whole point: c2 - D maps to card 37 (Kh) in the
    // encoding table. The contract checks the named card rather than scanning
    // all 52, so naming the wrong one must fail -- the next test.
    let v = dleq();
    let (proof, public_inputs) = dleq_aggregate();
    assert(
        v.verify_card_reveal(
            proof.span(), public_inputs.span(), u256 { low: 0xb0067a5f8c495734c3e681d72a4774c7, high: 0x134e10872fc389c67c3d51ed71ad69b9 }, u256 { low: 0x3bdbed39460c0861a5bdec6e68eb922c, high: 0x29c680f2d511260273c0fcdb31a9e0eb }, 37,
        ),
        'card 37 not recovered',
    );
}

#[test]
fn test_browser_dleq_rejects_a_wrong_claimed_card() {
    let v = dleq();
    let (proof, public_inputs) = dleq_aggregate();
    assert(
        !v.verify_card_reveal(
            proof.span(), public_inputs.span(), u256 { low: 0xb0067a5f8c495734c3e681d72a4774c7, high: 0x134e10872fc389c67c3d51ed71ad69b9 }, u256 { low: 0x3bdbed39460c0861a5bdec6e68eb922c, high: 0x29c680f2d511260273c0fcdb31a9e0eb }, 38,
        ),
        'wrong card accepted',
    );
}

#[test]
fn test_browser_dleq_rejects_a_tampered_share() {
    // d_x is public_inputs[8]. Moving the share breaks log_H(D) while leaving
    // log_G(PK) intact -- exactly the lie DLEQ exists to catch.
    let v = dleq();
    let (proof, public_inputs) = dleq_aggregate();
    let mut bad: Array<felt252> = array![];
    let mut i = 0;
    while i < public_inputs.len() {
        if i == 8 { bad.append(*public_inputs.at(i) + 1); } else { bad.append(*public_inputs.at(i)); }
        i += 1;
    }
    assert(!v.verify_decryption_share(proof.span(), bad.span()), 'tampered share accepted');
}

// -- Rejection here is a PANIC, not a 'false' -------------------------
//
// s is proof[0..1] and also the scalar the first MSM hint was built for.
// Moving it leaves the hint describing a different multiplication, and
// Garaga's msm_g1 asserts on that inconsistency rather than returning a
// value -- so the call reverts with 'Wrong FakeGLV decomposition' instead of
// verifying to false.
//
// That is safe HERE and it was checked rather than assumed: all five places
// PokerGame calls a verifier end in assert(..) (register_shuffle_key,
// begin_shuffle, submit_shuffle, answer_accusation, open_deck), so a panic
// and a 'false' both revert the transaction with no state written and no
// reentrancy lock stranded. In particular answer_accusation leaves the
// accusation uncleared either way, which is the outcome that matters.
//
// The difference is diagnostic: the caller sees a Garaga assertion string
// rather than BAD_SHARE_PROOF. Anything that ever wants to CONTINUE on a
// false -- rather than revert -- must not assume it will get one.
#[test]
#[should_panic(expected: ('Wrong FakeGLV decomposition', 'ENTRYPOINT_FAILED'))]
fn test_browser_dleq_rejects_a_tampered_response() {
    let v = dleq();
    let (proof, public_inputs) = dleq_aggregate();
    let mut bad: Array<felt252> = array![];
    let mut i = 0;
    while i < proof.len() {
        if i == 0 { bad.append(*proof.at(i) + 1); } else { bad.append(*proof.at(i)); }
        i += 1;
    }
    v.verify_decryption_share(bad.span(), public_inputs.span());
}

// A single party's share carries their own pk, not the joint key. Pairing one
// party's proof with the aggregate's public inputs is the shape of a party
// claiming credit for everyone's contribution. It is refused -- again by
// panic, for the reason above: the hint was built for this party's pk and the
// substituted inputs name a different point.
#[test]
#[should_panic(expected: ('wrong FakeGLV result', 'ENTRYPOINT_FAILED'))]
fn test_browser_dleq_individual_proof_does_not_verify_as_the_aggregate() {
    let v = dleq();
    let (proof, _) = dleq_individual();
    let (_, agg_inputs) = dleq_aggregate();
    v.verify_decryption_share(proof.span(), agg_inputs.span());
}
