// Generated by Garaga version 1.1.0

//! # Starknet Verification Contract Tests
//!
//! This module contains comprehensive tests for the proof verification contract.
//! The tests use Starknet Foundry's testing features to verify proofs.
//!
//! ## Test Strategy
//! - Use real proof fixtures generated by the garaga CLI
//! - Test both positive (valid proof) and negative (invalid proof) cases

use shuffle_open_verifier::honk_verifier::{
    IUltraKeccakZKHonkVerifierDispatcherTrait, IUltraKeccakZKHonkVerifierLibraryDispatcher,
};
use snforge_std::fs::{FileTrait, read_txt};
use snforge_std::{DeclareResultTrait, declare};
use starknet::ClassHash;

/// Declare the UltraKeccakZKHonkVerifier contract for testing.
///
/// This function declares a new instance of the UltraKeccakZKHonkVerifier contract
///
/// # Arguments
/// * `name` - The contract name to declare
///
/// # Returns
/// * `ClassHash` - The class hash of the declared contract
///
/// # Example
/// ```cairo
/// let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
/// let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
/// ```
fn declare_contract(name: ByteArray) -> ClassHash {
    let class_hash = *declare(name).unwrap().contract_class().class_hash;
    class_hash
}

/// Test the verification function verify_ultra_keccak_zk_honk_proof with a valid proof.
///
/// This test demonstrates the complete verification flow:
/// 1. Declare the verification contract
/// 2. Load a pre-generated proof fixture
/// 3. Verify the proof on-chain
/// 4. Assert that verification succeeds
///
/// ## Test Setup
/// - Uses fork testing against Sepolia testnet to access required declared contracts maintained by
/// the garaga team - Loads proof calldata from `tests/proof_calldata.txt`
/// - To generate the calldata, you can use the garaga CLI:
/// ```bash
/// garaga calldata
///     --system ultra_keccak_zk_honk
///     --vk path/to/vk
///     --proof path/to/proof
///     --public-inputs path/to/public_inputs
///     --format snforge
///     --output-path path/to/tests
/// ```
/// This will generate a file `proof_calldata.txt` in the specified output path.
/// You can then use this file in the test.
///
/// ## Expected Behavior
/// - The proof should verify successfully
/// - The function should return Ok(public_inputs) containing the expected public inputs
/// - No panics or assertion failures should occur
#[test]
#[fork(url: "https://api.zan.top/public/starknet-sepolia/rpc/v0_10", block_tag: latest)]
fn test_verify_ultra_keccak_zk_honk_proof() {
    // Step 1: Declare the verification contract
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };

    // Step 2: Load the proof fixture generated by the script
    // This file contains the ultra_keccak_zk_honk proof calldata formatted for Starknet
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    // Step 3: Verify the proof on-chain
    // This calls the contract's verify_ultra_keccak_zk_honk_proof function with the loaded proof
    // data
    let result = dispatcher.verify_ultra_keccak_zk_honk_proof(calldata);

    // Step 4: Assert that verification succeeded
    // A valid proof should return Ok(public_inputs), not Err
    assert(result.is_ok(), 'Proof verification failed');
    // Optional: You can also verify the public inputs contain expected values
// let public_inputs = result.unwrap();
// assert(public_inputs.len() > 0, 'No public inputs');
// Additional assertions on the public input values can be added here
}


// The public inputs, in the exact order PokerGame::submit_final_shuffle
// rebuilds them: the shuffle's four (pk_x, pk_y, hash_in, hash_out), then the
// opening's chunk and k_total, then 4K ciphertext coordinates.
//
// This is the join that the whole optimisation rests on: `hash_out` is BOTH
// the shuffle's output commitment and the deck-open circuit's `deck_hash`, so
// one proof binds the shuffled deck and its opening together. If these two
// halves ever drifted apart the contract would accept an opening of a deck
// nobody shuffled, so the layout is pinned here rather than assumed.
#[test]
fn test_public_inputs_are_shuffle_then_chunk_ktotal_then_cards() {
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    let public_inputs = dispatcher.verify_ultra_keccak_zk_honk_proof(calldata).unwrap();

    // 4 shuffle + chunk + k_total + 76 card coordinates. One under garaga's
    // usable budget of 83 (99 minus the 16 pairing-accumulator inputs it adds
    // on its own), which is exactly why K is 19 and not 20.
    assert(public_inputs.len() == 82, 'expected 82 public inputs');

    // hash_in / hash_out are the SAME pair circuits/shuffle_verifier proves
    // for this witness -- the merged circuit is the plain shuffle plus an
    // opening, not a different shuffle.
    let hash_in = *public_inputs.at(2);
    assert(hash_in.low == 0x384f864efedf56f0bf46e35b78bd0609, 'hash_in.low');
    assert(hash_in.high == 0x2c38e979e36182d8a5b09094e24daa44, 'hash_in.high');

    // ..and hash_out is also the deck_open fixture's deck_hash. That equality
    // is the binding: one public input serving as both circuits' deck.
    let hash_out = *public_inputs.at(3);
    assert(hash_out.low == 0xa85df438603c5f8f125591cd11c3924c, 'hash_out.low');
    assert(hash_out.high == 0x2d798b5c7a8e54145afc8db09e99c48f, 'hash_out.high');

    // The fixture is chunk 0 of a three-seat table: k_total = 2*3 + 5 = 11.
    assert(*public_inputs.at(4) == 0_u256, 'chunk is 0');
    assert(*public_inputs.at(5) == 11_u256, 'k_total is 11');

    // K = 19 covers slots 0..18, but only 0..10 are in play, so every slot
    // from the twelfth onwards repeats position 10. open_deck derives the
    // same padding independently; a disagreement would write the wrong
    // ciphertext to the wrong deck position, so it is pinned on both sides.
    let mut i: u32 = 11;
    while i != 19 {
        let mut f: u32 = 0;
        while f != 4 {
            assert(
                *public_inputs.at(6 + 4 * i + f) == *public_inputs.at(6 + 4 * 10 + f),
                'padding repeats slot 10',
            );
            f += 1;
        }
        i += 1;
    }
}

// Rejection is a PANIC, not an Err -- same as the other two verifiers, and
// for the same reason: Garaga's MSM hints are derived from the proof, so
// corrupting it desynchronises them before any pairing check runs. Safe at
// every PokerGame call site, all of which assert on the result.
//
// The message is deliberately NOT pinned, unlike the sibling verifiers'
// copies of this test. It is not stable across corruption sites: flipping
// felt 12 here reports 'Wrong GLV/FakeGLV decomposition' and felt 200 reports
// 'proof point not on curve'. Both are rejections, which is the property that
// matters; asserting one of garaga's internal strings would pin an
// implementation detail and would not detect an accepted bad proof any better
// than this does.
#[test]
#[should_panic]
fn test_rejects_a_corrupted_proof() {
    let class_hash = declare_contract("UltraKeccakZKHonkVerifier");
    let dispatcher = IUltraKeccakZKHonkVerifierLibraryDispatcher { class_hash };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file);

    // Index 12 is deliberately NOT the felt to hit here, unlike the sibling
    // verifiers' copies of this test: this circuit's public inputs are longer,
    // and felt 12 lands on k_total's high limb -- a zero. Corrupting a public
    // input tests the adapter's business, not the verifier's. Reach past the
    // 1 + 2*82 header into the proof body, where flipping a bit desynchronises
    // the MSM hints, which is the rejection this test is about.
    let mut corrupted: Array<felt252> = array![];
    let mut i = 0;
    while i < calldata.len() {
        if i == 200 {
            corrupted.append(*calldata.at(i) + 1);
        } else {
            corrupted.append(*calldata.at(i));
        }
        i += 1;
    }

    dispatcher.verify_ultra_keccak_zk_honk_proof(corrupted.span());
}
