#!/usr/bin/env python3
"""Generates real Grumpkin key shares and their sum, for the joint-key check.

`VerifierAdapter::verify_joint_key` sums a table's registered key shares on
Grumpkin and compares against the joint key the dealer supplied to
`begin_shuffle`. That is the check that stops a dealer imposing a key of
their own choosing and reading every hole card at the table
(security-review-20260904-round8-four-agent.md, "still open" #1).

The mock verifier in cairo/tests/ cannot do curve arithmetic, so it only
covers how PokerGame handles the answer. This produces the fixtures that
check the ARITHMETIC, consumed by cairo-verifier/tests/test_joint_key.cairo.

Pure Python on purpose: garaga's Python package is not a project dependency
and Grumpkin needs nothing beyond modular arithmetic.

  Grumpkin: y^2 = x^3 - 17 over F_p, where p is BN254's SCALAR field.
  (Its base and scalar fields are BN254's swapped -- that is the whole
  reason the protocol uses it; see docs/PROTOCOL.md section 2.1.)
"""

import argparse
import random

P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
N = 21888242871839275222246405745257275088696311157297823662689037894645226208583
A = 0
B = -17 % P
# Grumpkin's standard generator.
GX = 1
GY = 17631683881184975370165255887551781615748388533673675138860


def on_curve(pt):
    if pt is None:
        return True
    x, y = pt
    return (y * y - x * x * x - B) % P == 0


def add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    x1, y1 = p
    x2, y2 = q
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    if p == q:
        lam = (3 * x1 * x1) * pow(2 * y1, P - 2, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, P - 2, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def mul(k, p):
    r, acc = None, p
    k %= N
    while k:
        if k & 1:
            r = add(r, acc)
        acc = add(acc, acc)
        k >>= 1
    return r


def u256(v):
    return v & (2**128 - 1), v >> 128


def cairo_u256(v):
    lo, hi = u256(v)
    return f"u256 {{ low: {lo}, high: {hi} }}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--parties", type=int, default=3)
    ap.add_argument("--seed", type=int, default=20260904)
    ap.add_argument(
        "--as-array",
        action="store_true",
        help="emit a Cairo fn returning the shares as one Span<u256>, for "
        "large party counts where one const per coordinate is unreadable",
    )
    args = ap.parse_args()

    G = (GX, GY)
    assert on_curve(G), "generator is not on the curve"
    assert mul(N, G) is None, "generator order is wrong"

    rng = random.Random(args.seed)
    secrets = [rng.randrange(1, N) for _ in range(args.parties)]
    shares = [mul(x, G) for x in secrets]
    joint = None
    for s in shares:
        assert on_curve(s)
        joint = add(joint, s)
    assert on_curve(joint)
    # Y = (sum of secrets) * G -- the property the adapter is really
    # asserting, checked here independently of the point-by-point sum.
    assert joint == mul(sum(secrets) % N, G), "sum of shares != sum of secrets * G"

    print(f"// {args.parties} shares, seed {args.seed}. Generated by scripts/joint_key_check.py.")
    if args.as_array:
        print(f"fn max_shares() -> Span<u256> {{")
        print("    array![")
        for s_ in shares:
            print(f"        {cairo_u256(s_[0])},")
            print(f"        {cairo_u256(s_[1])},")
        print("    ]")
        print("        .span()")
        print("}")
        print(f"const MAX_JOINT_X: u256 = {cairo_u256(joint[0])};")
        print(f"const MAX_JOINT_Y: u256 = {cairo_u256(joint[1])};")
        return
    for i, s in enumerate(shares):
        print(f"const PK{i}_X: u256 = {cairo_u256(s[0])};")
        print(f"const PK{i}_Y: u256 = {cairo_u256(s[1])};")
    print(f"const JOINT_X: u256 = {cairo_u256(joint[0])};")
    print(f"const JOINT_Y: u256 = {cairo_u256(joint[1])};")
    neg = (joint[0], (-joint[1]) % P)
    print(f"// -Y: same x, different key. Must be rejected.")
    print(f"const NEG_JOINT_Y: u256 = {cairo_u256(neg[1])};")


if __name__ == "__main__":
    main()
